name: muonroi_friends
description: "Project connect and look distant friends."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.10
  dio: ^5.4.1
  vietmap_flutter_gl: ^1.3.9
  dartz: ^0.10.1
  google_fonts: ^6.2.0
  material_color_utilities: 0.8.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  equatable: ^2.0.5
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  google_sign_in: ^6.2.1
  pin_code_fields: ^8.0.1
  country_pickers: ^2.0.0
  sms_autofill: ^2.3.1
  staggered_grid_view_flutter: ^0.0.4
  connectivity_plus: ^5.0.2
  flutter_localizations:
    sdk: flutter
  calendar_date_picker2: ^0.5.5
  image_picker: ^1.0.7
  mime_type: ^1.0.0
  appinio_swiper: ^2.1.0
  carousel_slider: ^4.2.1
  url_launcher: ^6.2.5
  vietmap_gl_platform_interface: ^0.1.5
  vietmap_navigation_platform_interface: ^0.0.2
  flutter_dotenv: ^5.1.0
  flutter_xlider: ^3.5.0
  change_app_package_name: ^1.1.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_app_check: ^0.2.1+17
  sprintf: ^7.0.0
  percent_indicator:
    git:
      url: https://github.com/muonroi/flutter_percent_indicator.git
      ref: feature/add_function_return_percent_value
  flutter_image_slideshow: ^0.1.6
  bottom_sheet: ^4.0.1
  flutter_touch_ripple: ^1.1.21
  video_player: ^2.8.3
  flutter_chat_ui: ^1.6.12
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - .env
  fonts:
    
    - family: Poppins      
      fonts:         
        - asset: assets/fonts/Poppins-SemiBold.ttf          
          weight: 600        
        - asset: assets/fonts/Poppins-Regular.ttf          
          weight: 400    
    - family: Hellix      
      fonts:         
        - asset: assets/fonts/Hellix-ExtraBold.ttf          
          weight: 800        
        - asset: assets/fonts/Hellix-Medium.ttf          
          weight: 400        
        - asset: assets/fonts/Hellix-SemiBold.ttf          
          weight: 600        
        - asset: assets/fonts/Hellix-Bold.ttf          
          weight: 700        
        - asset: assets/fonts/Hellix-Regular.ttf          
          weight: 400
    - family: ChatMessage      
      fonts:         
        - asset: assets/fonts/ChatMessage.ttf          